Coursera/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import  handler404, handler403, handler500

handler404 = 'courses.views.view_404'
handler500 = 'courses.views.view_500'
handler403 = 'courses.views.view_403'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls',namespace='courses')),
    path('', include('blog.urls',namespace='blogs')),
    path('', include('memberships.urls',namespace='memberships')),
    path('', include('users.urls',namespace='users')),
    path('accounts/', include('allauth.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from blog.views import PostListView,PostDetailView, create_post, delete_post

app_name = 'blogs'

urlpatterns = [

    path("blog/",PostListView.as_view(),name='post_list'),
    path('blog/<int:pk>/',PostDetailView.as_view(),name='post_detail'),
    path('blog/create/', create_post, name='create_post'),
    path('blog/<int:id>/delete', delete_post, name='delete_post'),


]

courses/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from courses.views import HomeView,AboutView,ContactView,CourseListView, CourseDetailView,LessonDetailView, SearchView, krijo_klase, krijo_lende, krijo_mesim

app_name = 'courses'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('courses/<int:category>', CourseListView, name='course_list'),
    path('courses/<slug>/', login_required(CourseDetailView.as_view()), name='course_detail'),
    path('courses/<course_slug>/<lesson_slug>/', login_required(LessonDetailView.as_view()), name='lesson_detail'),
    path('search/', SearchView, name='kerko_kurs'),
    path('krijo/klase', krijo_klase, name='krijo_klase'),
    path('krijo/lende', krijo_lende, name='krijo_lende'),
    path('krijo/mesim', krijo_mesim, name='krijo_mesim')
]

users/urls.py
from django.urls import path

from users.views import Profile, kerkesa

app_name = 'users'

urlpatterns = [
    path('profile/', Profile, name='profile'),
    path('kerkesa/', kerkesa, name='kerkesa')

]

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- Page info -->
<div class="page-info-section set-bg" data-setbg="{% static 'webuni/img/page-bg/4.jpg' %}">
  <div class="container">
    <div class="site-breadcrumb">
      <a href="/">Главная</a>
      <span>о нас</span>
    </div>
  </div>
</div>
<!-- Page info end -->


<section class="about-us py-5 " id="about-us">
    <div class="container mt-5">
	<div class="row">
		<div class="col-md-6">
		    <h1 class='text-primary'>Привет!</h1>
		    <h2>Добро пожаловать на нашу образовательную платформу! </h2>
		    <hr>
		    <p>Мы стремимся предоставить качественное образование в доступной и удобной форме. У нас вы найдете множество видео и текстовых курсов по различным темам, которые помогут вам улучшить свои навыки и расширить кругозор.</p>
			<p>Мы понимаем, что обучение может быть трудным и утомительным, поэтому мы сделали все возможное, чтобы наша платформа была интуитивно понятной </p>
			<button type="button" class="btn btn-primary">Вперёд к знаниям!</button>

		</div>
		<div class="col-md-6">
		    <img src="http://themebubble.com/demo/marketingpro/wp-content/uploads/2016/10/seo-slide.png "alt="">
		</div>
	</div>
</div>
</section>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>F education</title>
	<meta charset="UTF-8">
	<meta name="description" content="WebUni Education Template">
	<meta name="keywords" content="webuni, education, creative, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link href="{% static 'webuni/img/favicon.png' %}" rel="shortcut icon"/>

	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,500,500i,600,600i,700,700i,800,800i" rel="stylesheet">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="{% static 'webuni/css/bootstrap.min.css'%}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/font-awesome.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/owl.carousel.css' %}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/style.css'%}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/freelancer.css'%}"/>
	<link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />


	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<nav class="navbar navbar-expand-lg bg-secondary text-uppercase" id="mainNav">
		<div class="container">
		  <a class="navbar-brand js-scroll-trigger" href="/"><img src="{% static 'webuni/img/logo2.png' %}" alt=""></a>
		  <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
			Менб
	
		  </button>
		  <div class="collapse navbar-collapse" id="navbarResponsive">
			<ul class="navbar-nav ml-auto">
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:home' %}">Главная</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<li class="nav-item mx-0 mx-lg-1">
					<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="/#kurset">Курсы</a>
				  </li>
			  </li>
			  {% if request.user.profile.is_teacher == True %}
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:krijo_klase' %}">Создать классы</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:krijo_lende' %}">Создать группу</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:krijo_mesim' %}">Создать</a>
			  </li>
			  {% else %}
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:contact' %}">Контакты</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:about' %}">О нас</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'blogs:post_list' %}">Блог</a>
			  </li>
			  {% endif %}
			  {% if request.user.is_authenticated %}
			  
			  <div class="dropdown show">
				<a class=" dropdown-toggle nav-link py-3 px-0 px-lg-3 rounded js-scroll-triggeraa" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					{{request.user.username}}
				</a>
			  
				<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
				  <a class="dropdown-item" href="{% url 'users:profile' %}">Профиль</a>
				  <a class="dropdown-item" href="{% url 'account_logout' %}">Выход</a>
				</div>
			  </div>
			  {% else %}
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="active nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'account_login' %}">Вход</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="active nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'account_signup' %}">Регистрация</a>
			  </li>
              {% endif %}
			</ul>
		  </div>
		</div>
	  </nav>

{% include 'inc/messages.html' %}
{% block content %}

{% endblock content %}

{% if request.user.is_authenticated %}
{% else %}
	<!-- banner section -->
	<section class="banner-section spad">
		<div class="container">
			<div class="section-title mb-0 pb-2">
				<h2>Присоединяйтесь к нашему сообществу!</h2>
				<p>Meso онлайн-лекции и уроки бесплатно через видео и общение с учителями и другими участниками сообшества. Это очень просто, единственное, что вам нужно сделать, это зарегистрироваться. Нажмите ниже:</p>
			</div>
			<div class="text-center pt-5">
				<a href="{% url 'account_signup' %}" class="site-btn">Регистрация</a>
			</div>
		</div>
	</section>
	<!-- banner section end -->
{% endif %}


	<!-- footer section -->
	<footer class="footer-section spad pb-0">
		<div class="footer-top">
			<div class="footer-warp">
				<div class="row">
					<div class="widget-item">
						<h4>Контактная информация</h4>
						<ul class="contact-list">
							<li>Худжанд <br>33, 71/13</li>
							<li>+992 92 9555283</li>
							<li>valijonzodafirdavs@gmail.com</li>
						</ul>
					</div>
					<div class="widget-item">
						<h4>Курсы</h4>
						<ul>
							<li><a href="">ВЕБ</a></li>
							<li><a href="">Дизайн</a></li>
							<li><a href="">Математика</a></li>
							<li><a href="">JavaScript</a></li>
							<li><a href="">FullS</a></li>
						</ul>
					</div>
					<div class="widget-item">
						<h4>Участники</h4>
						<ul>
							<li><a href="">Учителя</a></li>
							<li><a href="">Студенты</a></li>
							<li><a href="">Редакторы</a></li>
							<li><a href="">Читатели</a></li>
							
						</ul>
					</div>
					<div class="widget-item">
						<h4>Социальные сети</h4>
						<ul>
							<li><a href="">YouTube</a></li>
							<li><a href="">Facebook</a></li>
							<li><a href="">Instagram</a></li>
							<li><a href="">Twitter</a></li>

					
						</ul>
					</div>
					<div class="widget-item">
						<h4>последние новости</h4>
						<form class="footer-newslatter">
							<input type="email" placeholder="E-mail">
							<button class="site-btn">подписадся</button>
							<p>* Получайте последние новости, подписавшись</p>
						</form>
					</div>
				</div>
			</div>
		</div>
		<div class="footer-bottom">
			<div class="footer-warp">
				<ul class="footer-menu">
					<li><a href="#">Условия</a></li>
					<li><a href="#">Регистрация</a></li>
					<li><a href="#">Политика конфиденсиальности</a></li>
				</ul>
				<div class="">
	Copyright &copy; F education <script>document.write(new Date().getFullYear());</script> All rights reserved.
</div>
			</div>
		</div>
	</footer>
	<!-- footer section end -->


	<!--====== Javascripts & Jquery ======-->
	<script src="{% static 'webuni/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'webuni/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'webuni/js/mixitup.min.js' %}"></script>
	<script src="{% static 'webuni/js/circle-progress.min.js' %}"></script>
	<script src="{% static 'webuni/js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'webuni/js/main.js' %}"></script>
	<script src="{% static 'webuni/js/freelancer.js' %}"></script>
	<script src="https://unpkg.com/aos@next/dist/aos.js"></script>
  <script>
    AOS.init();
  </script>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<!-- Page info -->
<div class="page-info-section set-bg" data-setbg="{% static 'webuni/img/page-bg/4.jpg' %}">
  <div class="container">
    <div class="site-breadcrumb">
      <a href="/">Главная</a>
      <span>Контакты</span>
    </div>
  </div>
</div>

<section class="search-section ss-other-page">
  <div class="container">
    <div class="search-warp">
      <div class="section-title text-white">
        <h2><span>Мои курсы</span></h2>
      </div>
      <div class="row">
        <div class="col-lg-10 offset-lg-1">
          <!-- search form -->
          <form class="course-search-form">
            <input type="text" placeholder="Курс">
            <input type="text" class="last-m" placeholder="Категории">
            <button class="site-btn btn-dark">Поиск</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- search section end -->



<!-- Page -->
<section class="contact-page spad pb-0">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <div class="contact-form-warp">
          <div class="section-title text-white text-left">
            <h2>Связаться</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris scelerisque, at rutrum nulla dictum. Ut ac ligula sapien. </p>
          </div>
          <form class="contact-form">
            <input type="text" placeholder="Имя">
            <input type="text" placeholder=" E-mail">
            <input type="text" placeholder="причина">
            <textarea placeholder="Сообшение"></textarea>
            <button class="site-btn">Отправить</button>
          </form>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="contact-info-area">
          <div class="section-title text-left p-0">
            <h2>Контактная информация</h2>
            <p>Данные для связи с создателем</p>
          </div>
          <div class="phone-number">
            <span>Телефон</span>
            <h2>+992 929555283</h2>
          </div>
          <ul class="contact-list">
            <li>Худжанд,<br>33,71/13</li>
            <li>+99298544654654</li>
            <li>valijonzodafirdavs@gmail.com</li>
          </ul>
          <div class="social-links">
            <a href="#"><i class="fa fa-pinterest"></i></a>
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-dribbble"></i></a>
            <a href="#"><i class="fa fa-behance"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Page end -->

{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<!-- Hero section -->
<section class="hero-section set-bg" data-setbg="{% static 'webuni/img/bg.jpg'%}">
  <div class="container">
    <div class="hero-text text-white">
      {% if request.user.is_authenticated %}
      <h2>Привет {% if request.user.profile.is_teacher == True %}
         mesues,
        {% endif %} {{ request.user.username|capfirst }}

       
      </h2>
      {% else %}
      <h2>Прокачай свой кодинг-скилл с нами!</h2>
      {% endif %}
      <p>Преврати свой потенциал в профессиональный успех с F_education </p>
    </div>
    <div class="row">
      <div class="col-lg-10 offset-lg-1">
        <form method="post" action="{% url 'courses:kerko_kurs' %}" class="intro-newslatter"> {% csrf_token %}
          <input name="search" type="text" placeholder="поиск...">
          <button type="submit" class="site-btn">Поиск</button>
        </form>
      </div>
    </div>
  </div>
</section>
<!-- Hero section end -->

<!-- categories section -->
<section class="categories-section spad">
  <div class="container">
    <div class="section-title">
      <h2 id="kurset">Категории и классы</h2>
      <p>Уроки разделены на разные категории в соответствии с их классами и уровнем. Вы должны сначала зарегистрироваться, а затем посещать класс, к которому он принадлежит.</p>
    </div>
    <div class="row">
      {% for cat in category %}
      <!-- categorie -->
      <div data-aos="zoom-in" class="col-lg-4 col-md-6">
        <div class="categorie-item">
          <div class="ci-thumb set-bg" data-setbg="{{ cat.imazhi.url }}"></div>
          <div class="ci-text">

            <h5>{{cat.title|capfirst}}</h5>

            <p>{{ cat.pershkrimi|capfirst }}</p>
            <span><a class="btn btn-success" href="/courses/{{ cat.id }}">Посмотрите кейсы</a></span>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
<!-- categories section end -->
{% if request.user.is_authenticated %}
{% else %}
<section class="course-section spad">
  <div class="container">
    <div class="section-title mb-0">
      <h2>Примеры курсов</h2>
      <p class="pb-3">Вот несколько примеров курсов, которые студенты проходят на нашей платформе.</p>
    </div>
  </div>
  <div class="course-warp">                                     
    <div class="row course-items-area">
      <!-- course -->
      <div class="mix col-lg-3 col-md-4 col-sm-6 finance">
        <div class="course-item">
          <div class="course-thumb set-bg" data-setbg="{% static 'webuni/img/courses/4.jpg' %}">
            <iframe width="100%" height="290" src="https://www.youtube.com/embed/34Rp6KVGIEM"  frameborder="0" controls allowfullscreen></iframe>

          </div>
          <div class="course-info">
            <div class="course-text">
              <h5>Python</h5>
              <p></p>
              <div class="students">Язык Python для начинаюших</div>
            </div>
            <div class="course-author">
              <div class="ca-pic set-bg" data-setbg="{% static 'webuni/img/authors/4.jpg' %}"></div>
              <p>Азиза<span></span></p>
            </div>
          </div>
        </div>
      </div>
      <!-- course -->
      <div class="mix col-lg-3 col-md-4 col-sm-6 design">
        <div class="course-item">
          <div class="course-thumb set-bg" data-setbg="{% static 'webuni/img/courses/4.jpg' %}">
            <iframe width="100%" height="290" src="https://www.youtube.com/embed/mNJ06S60B9k?controls=0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </div>
          <div class="course-info">
            <div class="course-text">
              <h5>JavaScript</h5>
              <p>

              </p>
              <div class="students">JS-для ВЕБ разработки</div>
            </div>
            <div class="course-author">
              <div class="ca-pic set-bg" data-setbg="{% static 'webuni/img/authors/4.jpg' %}"></div>
              <p>Азиза, <span></span></p>
            </div>
          </div>
        </div>
      </div>
      <!-- course -->
      <div class="mix col-lg-3 col-md-4 col-sm-6 web">
        <div class="course-item">
          <div class="course-thumb set-bg" data-setbg="{% static 'webuni/img/courses/4.jpg' %}">
            <iframe width="100%" height="290" src="https://www.youtube.com/embed/3Q_oYDQ2whs?controls=0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </div>
          <div class="course-info">
            <div class="course-text">
              <p>
              </p>
              <h5>Аналитика даных</h5>
              <div class="students">Аналитика данных</div>
            </div>
            <div class="course-author">
              <div class="ca-pic set-bg" data-setbg="{% static 'webuni/img/authors/4.jpg' %}"></div>
              <p>Азиза <span></span></p>
            </div>
          </div>
        </div>
      </div>
      <!-- course -->
      <div class="mix col-lg-3 col-md-4 col-sm-6 photo">
        <div class="course-item">
          <div class="course-thumb set-bg" data-setbg="{% static 'webuni/img/courses/4.jpg' %}">
            <iframe width="100%" height="290" src="https://www.youtube.com/embed/LQFsEwcCO1E?controls=0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </div>
          <div class="course-info">
            <div class="course-text">
              <h5>Решение задач в Литкод</h5>
              <p></p>
              <div class="students">Анализируем код студентов</div>
            </div>
            <div class="course-author">
              <div class="ca-pic set-bg" data-setbg="{% static 'webuni/img/authors/4.jpg' %}"></div>
              <p>Азиза <span></span></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endif %}
<!-- course section end -->

{% if request.user.is_authenticated %}

<!-- signup section -->
{% if request.user.profile.is_teacher == True %}
<div class="container">
  <h1 class="text-center">У вашей учетной записи есть доступ для учителей</h1><br>
  <p class="text-center">Имея учетную запись учителя, вы теперь имеете более полный доступ к этой платформе. Вы можете выполнять больше функций, чем начальная учетная запись студента. Вот некоторые из этих функций:</p>

  <div data-aos="fade-right" class="row mt-4 mb-4 bg-light">
    <div class="col-md-4 text-center">
      <h3 class="p-4">Вы можете создать свой класс</h3>
      <a href="{% url 'courses:krijo_klase' %}" class="btn btn-outline-primary m-4">Создайте класс</a>
    </div>
    <div class="col-md-8">
      <img class="img-fluid w-100" src="{% static 'webuni/img/categories/4.jpg' %}" alt="">
    </div>
  </div>

  <div data-aos="fade-left" class="row mt-4 mb-4 bg-light">
      <div class="col-md-8">
        <img class="img-fluid w-100" src="{% static 'webuni/img/categories/2.jpg' %}" alt="">
      </div>
  
    <div class="col-md-4 text-center">
      <h3 class="p-4">Ju mund te krijoni lendet tuaja</h3> 
      <a href="{% url 'courses:krijo_lende' %}" class="btn btn-outline-primary m-4">Создать цепочку</a>
  </div>
</div>

<div data-aos="fade-right" class="row mt-4 mb-4 bg-light">
  <div class="col-md-4 text-center">
    <h3 class="p-4">Вы можете загружать свои уроки и видео.</h3>
    <a href="{% url 'courses:krijo_mesim' %}" class="btn btn-outline-primary m-4">Создать урок</a>
  </div>
  <div class="col-md-8">
    <img class="img-fluid w-100" src="{% static 'webuni/img/categories/1.jpg' %}" alt="">
  </div>
</div>
</div>

{% else %}
<section data-aos="zoom-out" class="signup-section spad">
  <div class="signup-bg set-bg" data-setbg="{% static 'webuni/img/signup-bg.jpg' %}"></div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-6">
        <div class="signup-warp">
          <div class="section-title text-white text-left">
            <h2>Зарегистрироваться как учитель</h2>
            <p>Чтобы зарегистрироваться в качестве учителя на платформе, вы должны заполнить поля ниже, после чего у вас будет полный доступ к загрузке курсов и видео.</p>
            
          </div>
          <!-- signup form -->
          <form action="/kerkesa/" method="post" class="signup-form">{% csrf_token %}
            <input type="text" placeholder="Ваше имя" name="name">
            <input type="text" placeholder="Email" name="e-mail">
            <input type="text" placeholder="Номер телефона" name="phone">
            <button class="site-btn">Регистрация</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

{% endif %}
<!-- signup section end -->
{% else %}
{% endif %}

{% endblock content %}